{
 "title": "Nginx Virtual Hosts Status",
 "tags": [
  "nginx",
  "nginx-module-vts"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(nginx_vts_server_bytes_total, instance)"
   },
   {
    "name": "Host",
    "query": "label_values(nginx_vts_server_requests_total{instance=~\"$Instance\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_vts_server_requests_total{instance=~\"$Instance\", host=~\"$Host\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(nginx_vts_server_bytes_total{instance=~\"$Instance\", host=~\"$Host\",direction=\"out\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(nginx_vts_server_bytes_total{instance=~\"$Instance\", host=~\"$Host\",direction=\"in\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Upstram",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\r\n  count without(job, instance, code) (\r\n    nginx_vts_filter_requests_total{instance=~\"$Instance\", filter=~\"upstream::.*\", filter=~\".*$Host\"}\r\n  ),\r\n  \"fqdn\",\r\n  \"$1\",\r\n  \"filter\",\r\n  \".*::(.*)\"\r\n)"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_vts_main_connections{instance=~\"$Instance\", status=~\"active|writing|reading|waiting\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top10 - URI",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum without(job, instance, filter, code) (\r\n    label_replace(\r\n      increase(nginx_vts_filter_requests_total{instance=~\"$Instance\", filter=~\"uri::.*\", filter=~\".*$Host\"}[$__range]),\r\n      \"fqdn\",\r\n      \"$1\",\r\n      \"filter\",\r\n      \".*::(.*)\"\r\n    ) > 0\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Status 2xx - QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_requests_total{instance=~\"$Instance\", host=~\"$Host\", code=\"2xx\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top10 - Status 4xx",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum without(job, instance, filter, code) (\r\n    label_replace(\r\n      increase(nginx_vts_filter_requests_total{instance=~\"$Instance\", filter=~\"uri::.*\", filter=~\".*$Host\", code=\"4xx\"}[$__range]),\r\n      \"fqdn\",\r\n      \"$1\",\r\n      \"filter\",\r\n      \".*::(.*)\"\r\n    ) > 0\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  irate(nginx_vts_server_bytes_total{instance=~\"$Instance\", host=~\"$Host\"}[$__range])\n) by (direction)"
    }
   ]
  },
  {
   "title": "Top10 -  Status 5xx",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum without(job, instance, filter, code) (\r\n    label_replace(\r\n      increase(nginx_vts_filter_requests_total{instance=~\"$Instance\", filter=~\"uri::.*\", filter=~\".*$Host\", code=\"5xx\"}[$__range]),\r\n      \"fqdn\",\r\n      \"$1\",\r\n      \"filter\",\r\n      \".*::(.*)\"\r\n    ) > 0\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Latancy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nginx_vts_server_request_seconds{instance=~\"$Instance\", host=~\"$Host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}