{
 "title": "Windows IIS Perfmon Metrics",
 "description": "Basic overview of windows host metrics, based on WMI Exporter (v0.13.0)",
 "tags": [ "windows_exporter" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_os_time, job)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(windows_iis_worker_threads{job=~\"$server.*\"}, app)"
   },
   {
    "name": "host",
    "label": "Hostname",
    "query": "label_values(windows_os_time{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests State",
   "type": "graph",
   "description": "Displays requests to WCF pools",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(windows_iis_worker_requests_total{}[5m])",
     "legendFormat": " {{instance}}: {{app}}"
    }
   ]
  },
  {
   "title": "WCFService Errors State $host",
   "type": "graph",
   "description": "Shows errors received in WCFService requests (when it received errors 400, 401,403,404 and 500)",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(windows_iis_worker_request_errors_total{}[5m])",
     "legendFormat": " {{instance}}:{{status_code}}: {{app}}"
    }
   ]
  },
  { "title": "Server IIS Perf $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "host" },
  {
   "title": "Pool State $host",
   "type": "bargauge",
   "description": "Shows the status of the application pool.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_iis_current_application_pool_state{state=\"Running\",instance=~\"$host\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Requests 500 Error $host",
   "type": "stat",
   "description": "Indicates that requests received 500",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_iis_worker_request_errors_total{status_code=\"500\",instance=~\"$host\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total Requests for WCFService Rate $host",
   "type": "stat",
   "description": "The average number of requests received in one minute to WCFService",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(windows_iis_worker_requests_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "IIS Connections Attempts $host",
   "type": "stat",
   "description": "Shows the number of minute connections attempted using the web service.",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(windows_iis_connection_attempts_all_instances_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP GET Requests $host",
   "type": "stat",
   "description": "Shows HTTP Get requests in minutes.",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(windows_iis_requests_total{method=~\"GET\",instance=~\"$host\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP POST Requests $host",
   "type": "stat",
   "description": "Shows HTTP Post requests in minutes.",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(windows_iis_requests_total{method=~\"POST\",instance=~\"$host\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IIS Max. Worker Process $host",
   "type": "stat",
   "description": "It shows the maximum number of processes in the IIS pool. When it is more than 1, it should be observed that the work is overloaded, to increase the work or to find a different solution.",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_iis_maximum_worker_processes{instance=~\"$host\"}",
     "legendFormat": "{{instance}}: {{app}}"
    }
   ]
  }
 ]
}