{
 "title": "Windows Server Overview",
 "tags": [
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(windows_cs_hostname, job)"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "label_values(windows_cs_hostname{job=~\"$job\"}, hostname)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(windows_cs_hostname{job=~\"$job\",hostname=~\"$hostname\"}, instance)"
   },
   {
    "name": "show_hostname",
    "label": "展示使用的主机名",
    "query": "label_values(windows_cs_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "資源總覽（關聯JOB）當前選中主機：【$show_hostname】實例：$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$job：伺服器資源總覽",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_cs_hostname"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\"}"
    },
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\"} - 0"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"$job\"})"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C:\"})"
    },
    {
     "expr": "max by (instance) (1-windows_logical_disk_free_bytes{job=~\"$job\"}/windows_logical_disk_size_bytes{job=~\"$job\"})"
    },
    {
     "expr": "windows_os_processes{job=~\"$job\"}"
    },
    {
     "expr": "sum by (instance) (windows_service_state{job=~\"$job\",state=~\"running\"})"
    }
   ]
  },
  {
   "title": "各主機CPU使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "各主機記憶體使用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "各主機最大流量網卡網路詳情",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "bps", "label": "下载　　　　上传" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_上传",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_net_bytes_received_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_下载",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "各主機最大磁盤讀寫詳情",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "读取　　　　写入" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_read_bytes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_读取",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_write_bytes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_写入",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "各主機最大磁盤IO詳情",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "yaxes": [
    { "format": "iops", "label": "读取　　　　写入" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_reads_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_读取",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_writes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_写入",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "資源明細【$show_hostname：$instance】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "啓動時長",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
     "repeat": "host",
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - windows_system_system_up_time{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "CPU使用率",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 - (avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[2m])))*100"
      }
     ]
    },
    {
     "title": "各磁碟使用率",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\"})*100",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "服務狀態",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(windows_service_state{job=~\"$job\",instance=~\"$instance\"}) by (state)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{state}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Process數",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "windows_os_processes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "进程数"
      }
     ]
    },
    {
     "title": "CPU核數",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "windows_cs_logical_processors{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Memory使用率",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 21 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 - (windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"})*100"
      }
     ]
    },
    {
     "title": "總記憶體",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 22 },
     "repeat": "host",
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "CPU使用率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[5m]))*100",
       "legendFormat": "CPU使用率"
      }
     ]
    },
    {
     "title": "Memory詳情",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "总物理内存",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "剩余物理内存",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_virtual_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Virtual memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "windows_os_virtual_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Free virtual memory"
      }
     ]
    },
    {
     "title": "磁盤剩餘空間",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "剩余空间 {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "总空间 {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "網路詳情",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_bytes_sent_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8>0\r",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}}-Sent-上传",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_bytes_received_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8\n",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}}-Received-下载",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "磁盤讀寫",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "磁盤IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_reads_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_writes_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "網路使用率",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(irate(windows_net_bytes_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m]) * 8 / windows_net_current_bandwidth{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}) * 100",
       "legendFormat": "{{nic}}"
      }
     ]
    },
    {
     "title": "Network discarded/error packets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_packets_outbound_discarded{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_outbound_errors{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "outbound",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_packets_received_discarded{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_received_errors{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "received",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "system_threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_system_threads{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "system_threads",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "System exception dispatches",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_system_exception_dispatches_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "exceptions",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  }
 ]
}